### ISSUE TITLE
Most procs require annotation of {.gcsafe.} to compile

### ISSUE THREAD

**Issue by ajusa** [dizzyliam/pigeon#2]
It might be possible to include a {.push gcsafe.} in the auto route block to prevent this issue?

**Comment by dizzyliam** [comment]
Could you give an example? I'm hesitant to apply pragmas to user-defined procs, as they may not actually be safe.

**Comment by ajusa** [comment]
```nim
import norm/[model, sqlite], pigeon
type Post* = ref object of Model
  text*: string

let db = open(":memory:", "", "", "")
db.createTables(Post())

autoRoute:
  proc getHello() = db.createTables(Post())
```

I believe that this is caused by the fact that I'm touching db, a global variable. I'm not actually sure if this is a bug, but I do know that jester handles this code without any errors/additional pragmas that the user has to add.

**Comment by dizzyliam** [comment]
I'm not sure why, because you're not compiling with threads on, but the compiler things `createTables` is unsafe, even though it is. [Here's a relevant discussion.](https://github.com/moigagoo/norm/issues/167) You'll have to mark the proc or the call as safe, like you've been doing. It would be a bad idea for pigeon to mark all procs as safe, because sometimes they wont be.

**Comment by ajusa** [comment]
Makes sense, thanks for looking into it!
